// Generates phone/js/data.js from the firmware's C sources (dex.h, i18n.h,
// i18n.cpp, species.h) so the phone port never drifts from the firmware.
// Usage: node phone/tools/extract.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const src = (f) => readFileSync(join(root, f), 'utf8');

// CP437 upper half: the firmware writes accents as octal bytes in this codepage
const CP437_HI =
  'ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐' +
  '└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ';

// Tokenizes a C initializer body into string literals (adjacent ones joined),
// nullptr and bare numbers/identifiers, in order.
function cTokens(body) {
  const out = [];
  let i = 0;
  let pendingStr = null;
  const flush = () => { if (pendingStr !== null) { out.push(pendingStr); pendingStr = null; } };
  while (i < body.length) {
    const ch = body[i];
    if (ch === '/' && body[i + 1] === '/') { while (i < body.length && body[i] !== '\n') i++; continue; }
    if (ch === '/' && body[i + 1] === '*') { i = body.indexOf('*/', i) + 2; continue; }
    if (ch === '"') {
      let s = '';
      i++;
      while (body[i] !== '"') {
        if (body[i] === '\\') {
          const n = body[i + 1];
          if (/[0-7]/.test(n)) {
            let oct = '';
            let j = i + 1;
            while (oct.length < 3 && /[0-7]/.test(body[j])) oct += body[j++];
            const b = parseInt(oct, 8);
            s += b >= 128 ? CP437_HI[b - 128] : String.fromCharCode(b);
            i = j;
            continue;
          }
          s += { n: '\n', t: '\t', '"': '"', '\\': '\\', "'": "'" }[n] ?? n;
          i += 2;
          continue;
        }
        s += body[i++];
      }
      i++;
      pendingStr = (pendingStr ?? '') + s;
      continue;
    }
    if (/[A-Za-z0-9_]/.test(ch)) {
      flush();
      let w = '';
      while (i < body.length && /[A-Za-z0-9_]/.test(body[i])) w += body[i++];
      out.push(w === 'nullptr' ? null : /^(0x[0-9a-fA-F]+|\d+)$/.test(w) ? Number(w) : w);
      continue;
    }
    if (ch === ',' || ch === '}' ) flush();
    i++;
  }
  flush();
  return out;
}

// body of `NAME[...] = { ... };`
function arrayBody(text, name) {
  const start = text.indexOf(name);
  if (start < 0) throw new Error('not found: ' + name);
  const open = text.indexOf('{', text.indexOf('=', start));
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}' && --depth === 0) return text.slice(open + 1, i);
  }
  throw new Error('unterminated: ' + name);
}

function chunk(arr, n) {
  const out = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
  return out;
}

// ---- dex.h ----
const dexH = src('dex.h');
const RARITY = { R_EVO: 0, R_COMUN: 1, R_RARO: 2, R_LEGENDARIO: 3 };
const dex = chunk(cTokens(arrayBody(dexH, 'DEX_TBL')), 10).map(
  ([name, evolvesTo, evolveLevel, rarity, accent, bHp, bAtk, bDef, bSpe, biome]) => ({
    name, evolvesTo, evolveLevel, rarity: RARITY[rarity] ?? rarity, accent, bHp, bAtk, bDef, bSpe, biome,
  }));
if (dex.length !== 152) throw new Error('DEX_TBL: expected 152 rows, got ' + dex.length);
const dexNames = {};
for (const l of ['FR', 'DE', 'JA', 'KO']) {
  const n = cTokens(arrayBody(dexH, 'DEX_NAME_' + l));
  if (n.length !== 152) throw new Error(`DEX_NAME_${l}: ${n.length}`);
  dexNames[l] = n;
}
const classic = cTokens(arrayBody(dexH, 'CLASSIC_DEX'));

// ---- i18n ----
const i18nH = src('i18n.h');
const enumBody = i18nH.slice(i18nH.indexOf('enum StrId'), i18nH.indexOf('STR_COUNT'));
const strIds = [...enumBody.replace(/\/\/.*$/gm, '').matchAll(/\bS_[A-Z0-9_]+/g)].map((m) => m[0]);
const i18nC = src('i18n.cpp');
const strings = chunk(cTokens(arrayBody(i18nC, 'STRINGS[')), strIds.length);
if (strings.length !== 8 || strings.some((r) => r.length !== strIds.length))
  throw new Error('STRINGS shape mismatch');
const medals = {};
for (const k of ['MED_NAME', 'MED_LBL', 'MED_DSC']) medals[k] = chunk(cTokens(arrayBody(i18nC, k + '[')), 8);

// ---- species.h: palette + char-map sprites ----
const spH = src('species.h');
const palette = {};
for (const m of spH.matchAll(/case '(.)': return (0x[0-9A-F]+);/g)) palette[m[1]] = Number(m[2]);
const maps = {};
for (const n of ['SPR_ICON_FOOD', 'SPR_ICON_PLAY', 'SPR_ICON_LIGHT', 'SPR_ICON_CLEAN',
  'SPR_ICON_BERRY_B', 'SPR_ICON_BERRY_G', 'SPR_ICON_CANDY', 'SPR_EGG', 'SPR_POOP', 'SPR_HEART']) {
  maps[n.replace('SPR_', '')] = cTokens(arrayBody(spH, n + '['));
}

const fw = src('TamaPoke.ino').match(/#define FW_VERSION "([^"]+)"/)[1];

const out = `// GENERATED by phone/tools/extract.mjs from the firmware sources. Do not edit.
export const FW_VERSION = ${JSON.stringify(fw)};
export const DEX = ${JSON.stringify(dex)};
export const DEX_NAMES = ${JSON.stringify(dexNames)};
export const CLASSIC_DEX = ${JSON.stringify(classic)};
export const STR_IDS = ${JSON.stringify(strIds)};
export const STRINGS = ${JSON.stringify(strings)};
export const MED_NAME = ${JSON.stringify(medals.MED_NAME)};
export const MED_LBL = ${JSON.stringify(medals.MED_LBL)};
export const MED_DSC = ${JSON.stringify(medals.MED_DSC)};
export const PALETTE = ${JSON.stringify(palette)};
export const MAPS = ${JSON.stringify(maps)};
`;
writeFileSync(join(root, 'phone', 'js', 'data.js'), out);
console.log(`data.js: ${dex.length - 1} species, ${strIds.length} strings x 8 langs, ${Object.keys(maps).length} maps, fw ${fw}`);
